spring:

  main:
    web-application-type: NONE

  cloud:
    stream:
      bindings:

        retries:
          destination: retries.topic
          contentType: application/json
          group: advanced
          consumer:
            maxAttempts: 6
            backOffInitialInterval: 500
            backOffMaxInterval: 3000

      rabbit:
        bindings:

          retries:
            consumer:
              autoBindDlq: true
              dlqTtl: 60000
              dlqDeadLetterExchange:
