spring:
  cloud:
    stream:
      bindings:

        aConsumer:
          destination: routed.topic
          contentType: application/json
          group: ${ROUTING_KEY}

      rabbit:
        bindings:

          aConsumer:
            consumer:
              bindingRoutingKey: ${ROUTING_KEY}

  main:
    web-application-type: NONE