spring:
  cloud:
    stream:
      bindings:

        main:
          destination: main.topic
          contentType: application/json
          group: advanced
          consumer:
            maxAttempts: 5
            backOffInitialInterval: 1000
            backOffMaxInterval: 6000

        backup:
          destination: backup.topic
          contentType: application/json
          group: advanced
          consumer:
            maxAttempts: 3
            backOffInitialInterval: 1000
            backOffMaxInterval: 6000

        routed:
          destination: routed.topic
          contentType: application/json

        greenroute:
          destination: routed.topic
          contentType: application/json
          group: green

        redroute:
          destination: routed.topic
          contentType: application/json
          group: red

      rabbit:
        bindings:

          main:
            consumer:
              autoBindDlq: true

          backup:
            consumer:
              autoBindDlq: true
              dlqTtl: 60000
              dlqDeadLetterExchange:

          routed:
            producer:
              routingKeyExpression: payload.color

          greenroute:
            consumer:
              bindingRoutingKey: green

          redroute:
            consumer:
              bindingRoutingKey: red

logging:
  level:
    root: INFO
    org.springframework.integration.handler.LoggingHandler: OFF
    org.springframework.amqp.rabbit.listener.ConditionalRejectingErrorHandler: ERROR
    org.springframework.amqp.rabbit.retry.RejectAndDontRequeueRecoverer: ERROR