spring:
  cloud:
    stream:
      bindings:

        aProducer:
          destination: routed.topic
          contentType: application/json

      rabbit:
        bindings:

          aProducer:
            producer:
              routingKeyExpression: payload.color
