spring:
  cloud:
    stream:
      bindings:

        main:
          destination: retries-with-dlq.topic
          contentType: application/json
          group: advanced
          consumer:
            maxAttempts: 3
            backOffInitialInterval: 500
            backOffMaxInterval: 3000

      rabbit:
        bindings:

          main:
            consumer:
              autoBindDlq: true

  main:
    web-application-type: NONE