logging:
  level:
    root: INFO
    org.springframework.integration.handler.LoggingHandler: OFF
    org.springframework.amqp.rabbit.listener.ConditionalRejectingErrorHandler: ERROR
    org.springframework.amqp.rabbit.retry.RejectAndDontRequeueRecoverer: ERROR
